"""baseline schema

Revision ID: f99dae6e6691
Revises: 
Create Date: 2026-04-27 17:41:59.741748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db.types


# revision identifiers, used by Alembic.
revision: str = 'f99dae6e6691'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('account_number_masked', sa.String(), nullable=True),
    sa.Column('envelope_owner', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('opening_balance', db.types.DecimalText(), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('bank','credit_card','cash_envelope','broker','mf','epf','nps')", name='ck_accounts_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_transfer', sa.Integer(), nullable=False),
    sa.Column('is_income', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_categories_name_parent')
    )
    op.create_table('nav_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_code', sa.String(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('nav', db.types.DecimalText(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code', 'nav_date', name='uq_nav_cache_scheme_date')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('units', db.types.DecimalText(), nullable=False),
    sa.Column('avg_cost', db.types.DecimalText(), nullable=True),
    sa.Column('total_invested', db.types.DecimalText(), nullable=False),
    sa.Column('current_nav', db.types.DecimalText(), nullable=True),
    sa.Column('current_value', db.types.DecimalText(), nullable=True),
    sa.Column('nav_updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("instrument_type IN ('mf','stock','fd','epf','nps','crypto')", name='ck_holdings_instrument_type'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'identifier', name='uq_holdings_account_identifier')
    )
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('source_format', sa.String(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_format IN ('pdf','csv','xlsx','manual')", name='ck_imports_source_format'),
    sa.CheckConstraint("status IN ('success','partial','failed')", name='ck_imports_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expected_amount', db.types.DecimalText(), nullable=True),
    sa.Column('amount_tolerance_pct', sa.Float(), nullable=False),
    sa.Column('cadence', sa.String(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('auto_detected', sa.Integer(), nullable=False),
    sa.CheckConstraint("cadence IN ('monthly','quarterly','annual','custom')", name='ck_subscriptions_cadence'),
    sa.CheckConstraint("status IN ('active','paused','cancelled')", name='ck_subscriptions_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=True),
    sa.Column('amount_min', db.types.DecimalText(), nullable=True),
    sa.Column('amount_max', db.types.DecimalText(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('txn_type', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('blacklist_until', sa.DateTime(), nullable=True),
    sa.CheckConstraint("created_by IN ('system','user')", name='ck_rules_created_by'),
    sa.CheckConstraint("pattern_type IN ('narration','vpa','prefix','token','exact')", name='ck_rules_pattern_type'),
    sa.CheckConstraint("status IN ('candidate','active','disabled','blacklisted')", name='ck_rules_status'),
    sa.CheckConstraint("txn_type IN ('debit','credit')", name='ck_rules_txn_type'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index('idx_rules_priority', ['priority'], unique=False)
        batch_op.create_index('idx_rules_status', ['status'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('amount', db.types.DecimalText(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('narration', sa.String(), nullable=False),
    sa.Column('narration_hash', sa.String(), nullable=False),
    sa.Column('balance_after', db.types.DecimalText(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('transfer_pair_id', sa.Integer(), nullable=True),
    sa.Column('is_transfer', sa.Integer(), nullable=False),
    sa.Column('classification_source', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('dup_group_id', sa.Integer(), nullable=True),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('raw_narration', sa.String(), nullable=True),
    sa.Column('raw_date_str', sa.String(), nullable=True),
    sa.Column('raw_amount_str', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("classification_source IN ('rule_t1','rule_t2','fuzzy_t3','manual','unclassified')", name='ck_transactions_classification_source'),
    sa.CheckConstraint("review_reason IN ('classification','duplicate','transfer')", name='ck_transactions_review_reason'),
    sa.CheckConstraint("type IN ('debit','credit')", name='ck_transactions_type'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['transfer_pair_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_txn_account_date', ['account_id', 'txn_date'], unique=False)
        batch_op.create_index('idx_txn_category', ['category_id'], unique=False)
        batch_op.create_index('idx_txn_date', ['txn_date'], unique=False)
        batch_op.create_index('idx_txn_dedup_lookup', ['account_id', 'txn_date', 'amount', 'narration_hash'], unique=False)
        batch_op.create_index('idx_txn_dup_group', ['dup_group_id'], unique=False, sqlite_where=sa.text('dup_group_id IS NOT NULL'))
        batch_op.create_index('idx_txn_review', ['needs_review'], unique=False, sqlite_where=sa.text('needs_review=1'))
        batch_op.create_index('idx_txn_subscription', ['subscription_id'], unique=False)

    op.create_table('holding_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('units', db.types.DecimalText(), nullable=False),
    sa.Column('price_per_unit', db.types.DecimalText(), nullable=True),
    sa.Column('amount', db.types.DecimalText(), nullable=False),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint("type IN ('buy','sell','dividend','split','bonus')", name='ck_holding_transactions_type'),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holding_transactions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_txn_subscription')
        batch_op.drop_index('idx_txn_review', sqlite_where=sa.text('needs_review=1'))
        batch_op.drop_index('idx_txn_dup_group', sqlite_where=sa.text('dup_group_id IS NOT NULL'))
        batch_op.drop_index('idx_txn_dedup_lookup')
        batch_op.drop_index('idx_txn_date')
        batch_op.drop_index('idx_txn_category')
        batch_op.drop_index('idx_txn_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index('idx_rules_status')
        batch_op.drop_index('idx_rules_priority')

    op.drop_table('rules')
    op.drop_table('subscriptions')
    op.drop_table('imports')
    op.drop_table('holdings')
    op.drop_table('nav_cache')
    op.drop_table('categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
